### ISSUE TITLE
SUGGEST returns a PENDING answer

### ISSUE THREAD

**Issue by athoune** [xmonader/python-sonic-client#13]
**Describe the bug**
When I use `SearchClient.suggest` method, the answer is `PENDING`.

**Expected behavior**
I expect the suggestion.

The answer is in the next message, see https://github.com/valeriansaliou/sonic/blob/master/PROTOCOL.md an `EVENT SUGGEST`.

**Comment by athoune** [comment]
Maybe `_execute_command` vs `_execute_command_async`

**Comment by matt-chv** [comment]
thanks, changing line 680 in client.py with your above suggestion fixed it
from within suggest(
> return self._execute_command(
to
> return self._execute_command_async(
gives expected results

**Comment by xmonader** [comment]
closing via https://github.com/xmonader/python-sonic-client/pull/14
